// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
