// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool flag = 3;</code>
   */
  boolean getFlag();

  /**
   * <code>map&lt;int64, string&gt; others = 4;</code>
   */
  int getOthersCount();
  /**
   * <code>map&lt;int64, string&gt; others = 4;</code>
   */
  boolean containsOthers(
      long key);
  /**
   * Use {@link #getOthersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.String>
  getOthers();
  /**
   * <code>map&lt;int64, string&gt; others = 4;</code>
   */
  java.util.Map<java.lang.Long, java.lang.String>
  getOthersMap();
  /**
   * <code>map&lt;int64, string&gt; others = 4;</code>
   */

  java.lang.String getOthersOrDefault(
      long key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;int64, string&gt; others = 4;</code>
   */

  java.lang.String getOthersOrThrow(
      long key);
}
