// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.test.netty.proto.Info infos = 1;</code>
   */
  java.util.List<com.test.netty.proto.Info> 
      getInfosList();
  /**
   * <code>repeated .com.test.netty.proto.Info infos = 1;</code>
   */
  com.test.netty.proto.Info getInfos(int index);
  /**
   * <code>repeated .com.test.netty.proto.Info infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated .com.test.netty.proto.Info infos = 1;</code>
   */
  java.util.List<? extends com.test.netty.proto.InfoOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <code>repeated .com.test.netty.proto.Info infos = 1;</code>
   */
  com.test.netty.proto.InfoOrBuilder getInfosOrBuilder(
      int index);
}
