// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public final class MyDemo {
  private MyDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_Info_OthersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_Info_OthersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_InfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_GreetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_People_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_People_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_PeopleList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_PeopleList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_StudentRequest_InfosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_StudentRequest_InfosEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_test_netty_proto_StudentList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_test_netty_proto_StudentList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016rpc_demo.proto\022\024com.test.netty.proto\"\036" +
      "\n\nMyResponse\022\020\n\010realname\030\001 \001(\t\"\027\n\tMyRequ" +
      "est\022\n\n\002id\030\001 \001(\005\"\032\n\013InfoRequest\022\013\n\003msg\030\001 " +
      "\001(\t\"\226\001\n\004Info\022\013\n\003age\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\014\n\004flag\030\003 \001(\010\0226\n\006others\030\004 \003(\0132&.com.test" +
      ".netty.proto.Info.OthersEntry\032-\n\013OthersE" +
      "ntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\t:\0028\001\"9\n\014" +
      "InfoResponse\022)\n\005infos\030\001 \003(\0132\032.com.test.n" +
      "etty.proto.Info\"\034\n\014GreetRequest\022\014\n\004name\030" +
      "\001 \001(\t\"*\n\rGreetResponse\022\013\n\003msg\030\001 \001(\t\022\014\n\004d" +
      "ate\030\002 \001(\t\"\035\n\rPeopleRequest\022\014\n\004name\030\001 \001(\t" +
      "\"U\n\006People\022\013\n\003age\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n" +
      "\006height\030\003 \001(\002\022\r\n\005money\030\004 \001(\001\022\021\n\tisMarrie" +
      "d\030\005 \001(\010\";\n\nPeopleList\022-\n\007peoples\030\001 \003(\0132\034" +
      ".com.test.netty.proto.People\"~\n\016StudentR" +
      "equest\022>\n\005infos\030\001 \003(\0132/.com.test.netty.p" +
      "roto.StudentRequest.InfosEntry\032,\n\nInfosE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"&\n\007" +
      "Student\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\">\n\013" +
      "StudentList\022/\n\010students\030\001 \003(\0132\035.com.test" +
      ".netty.proto.Student2\302\003\n\013DemoService\022P\n\013" +
      "GetUserById\022\037.com.test.netty.proto.MyReq" +
      "uest\032 .com.test.netty.proto.MyResponse\022Q" +
      "\n\010GetInfos\022!.com.test.netty.proto.InfoRe" +
      "quest\032\".com.test.netty.proto.InfoRespons" +
      "e\022U\n\010Greeting\022\".com.test.netty.proto.Gre" +
      "etRequest\032#.com.test.netty.proto.GreetRe" +
      "sponse(\001\022[\n\020GetPeoplesByName\022#.com.test." +
      "netty.proto.PeopleRequest\032 .com.test.net" +
      "ty.proto.PeopleList0\001\022Z\n\013GetStudents\022$.c" +
      "om.test.netty.proto.StudentRequest\032!.com" +
      ".test.netty.proto.StudentList(\0010\001B \n\024com" +
      ".test.netty.protoB\006MyDemoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_test_netty_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_test_netty_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_test_netty_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_test_netty_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_MyRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_test_netty_proto_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_test_netty_proto_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_InfoRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_com_test_netty_proto_Info_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_test_netty_proto_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_Info_descriptor,
        new java.lang.String[] { "Age", "Name", "Flag", "Others", });
    internal_static_com_test_netty_proto_Info_OthersEntry_descriptor =
      internal_static_com_test_netty_proto_Info_descriptor.getNestedTypes().get(0);
    internal_static_com_test_netty_proto_Info_OthersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_Info_OthersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_test_netty_proto_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_test_netty_proto_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_InfoResponse_descriptor,
        new java.lang.String[] { "Infos", });
    internal_static_com_test_netty_proto_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_test_netty_proto_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_GreetRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_test_netty_proto_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_test_netty_proto_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_GreetResponse_descriptor,
        new java.lang.String[] { "Msg", "Date", });
    internal_static_com_test_netty_proto_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_test_netty_proto_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_PeopleRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_test_netty_proto_People_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_test_netty_proto_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_People_descriptor,
        new java.lang.String[] { "Age", "Name", "Height", "Money", "IsMarried", });
    internal_static_com_test_netty_proto_PeopleList_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_test_netty_proto_PeopleList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_PeopleList_descriptor,
        new java.lang.String[] { "Peoples", });
    internal_static_com_test_netty_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_test_netty_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Infos", });
    internal_static_com_test_netty_proto_StudentRequest_InfosEntry_descriptor =
      internal_static_com_test_netty_proto_StudentRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_test_netty_proto_StudentRequest_InfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_StudentRequest_InfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_test_netty_proto_Student_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_test_netty_proto_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_Student_descriptor,
        new java.lang.String[] { "Name", "Score", });
    internal_static_com_test_netty_proto_StudentList_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_test_netty_proto_StudentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_test_netty_proto_StudentList_descriptor,
        new java.lang.String[] { "Students", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
