// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
