// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>float height = 3;</code>
   */
  float getHeight();

  /**
   * <code>double money = 4;</code>
   */
  double getMoney();

  /**
   * <code>bool isMarried = 5;</code>
   */
  boolean getIsMarried();
}
