// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface PeopleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.PeopleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  java.util.List<com.test.netty.proto.People> 
      getPeoplesList();
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  com.test.netty.proto.People getPeoples(int index);
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  int getPeoplesCount();
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  java.util.List<? extends com.test.netty.proto.PeopleOrBuilder> 
      getPeoplesOrBuilderList();
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  com.test.netty.proto.PeopleOrBuilder getPeoplesOrBuilder(
      int index);
}
