// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

/**
 * Protobuf type {@code com.test.netty.proto.PeopleList}
 */
public  final class PeopleList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.test.netty.proto.PeopleList)
    PeopleListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeopleList.newBuilder() to construct.
  private PeopleList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeopleList() {
    peoples_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PeopleList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              peoples_ = new java.util.ArrayList<com.test.netty.proto.People>();
              mutable_bitField0_ |= 0x00000001;
            }
            peoples_.add(
                input.readMessage(com.test.netty.proto.People.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        peoples_ = java.util.Collections.unmodifiableList(peoples_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.netty.proto.MyDemo.internal_static_com_test_netty_proto_PeopleList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.netty.proto.MyDemo.internal_static_com_test_netty_proto_PeopleList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.netty.proto.PeopleList.class, com.test.netty.proto.PeopleList.Builder.class);
  }

  public static final int PEOPLES_FIELD_NUMBER = 1;
  private java.util.List<com.test.netty.proto.People> peoples_;
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  public java.util.List<com.test.netty.proto.People> getPeoplesList() {
    return peoples_;
  }
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  public java.util.List<? extends com.test.netty.proto.PeopleOrBuilder> 
      getPeoplesOrBuilderList() {
    return peoples_;
  }
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  public int getPeoplesCount() {
    return peoples_.size();
  }
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  public com.test.netty.proto.People getPeoples(int index) {
    return peoples_.get(index);
  }
  /**
   * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
   */
  public com.test.netty.proto.PeopleOrBuilder getPeoplesOrBuilder(
      int index) {
    return peoples_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < peoples_.size(); i++) {
      output.writeMessage(1, peoples_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < peoples_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, peoples_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.netty.proto.PeopleList)) {
      return super.equals(obj);
    }
    com.test.netty.proto.PeopleList other = (com.test.netty.proto.PeopleList) obj;

    if (!getPeoplesList()
        .equals(other.getPeoplesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPeoplesCount() > 0) {
      hash = (37 * hash) + PEOPLES_FIELD_NUMBER;
      hash = (53 * hash) + getPeoplesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.netty.proto.PeopleList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.netty.proto.PeopleList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.netty.proto.PeopleList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.netty.proto.PeopleList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.netty.proto.PeopleList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.netty.proto.PeopleList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.netty.proto.PeopleList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.test.netty.proto.PeopleList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.test.netty.proto.PeopleList)
      com.test.netty.proto.PeopleListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.netty.proto.MyDemo.internal_static_com_test_netty_proto_PeopleList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.netty.proto.MyDemo.internal_static_com_test_netty_proto_PeopleList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.netty.proto.PeopleList.class, com.test.netty.proto.PeopleList.Builder.class);
    }

    // Construct using com.test.netty.proto.PeopleList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPeoplesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (peoplesBuilder_ == null) {
        peoples_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        peoplesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.netty.proto.MyDemo.internal_static_com_test_netty_proto_PeopleList_descriptor;
    }

    @java.lang.Override
    public com.test.netty.proto.PeopleList getDefaultInstanceForType() {
      return com.test.netty.proto.PeopleList.getDefaultInstance();
    }

    @java.lang.Override
    public com.test.netty.proto.PeopleList build() {
      com.test.netty.proto.PeopleList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.test.netty.proto.PeopleList buildPartial() {
      com.test.netty.proto.PeopleList result = new com.test.netty.proto.PeopleList(this);
      int from_bitField0_ = bitField0_;
      if (peoplesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          peoples_ = java.util.Collections.unmodifiableList(peoples_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.peoples_ = peoples_;
      } else {
        result.peoples_ = peoplesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.netty.proto.PeopleList) {
        return mergeFrom((com.test.netty.proto.PeopleList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.netty.proto.PeopleList other) {
      if (other == com.test.netty.proto.PeopleList.getDefaultInstance()) return this;
      if (peoplesBuilder_ == null) {
        if (!other.peoples_.isEmpty()) {
          if (peoples_.isEmpty()) {
            peoples_ = other.peoples_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePeoplesIsMutable();
            peoples_.addAll(other.peoples_);
          }
          onChanged();
        }
      } else {
        if (!other.peoples_.isEmpty()) {
          if (peoplesBuilder_.isEmpty()) {
            peoplesBuilder_.dispose();
            peoplesBuilder_ = null;
            peoples_ = other.peoples_;
            bitField0_ = (bitField0_ & ~0x00000001);
            peoplesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeoplesFieldBuilder() : null;
          } else {
            peoplesBuilder_.addAllMessages(other.peoples_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.netty.proto.PeopleList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.netty.proto.PeopleList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.test.netty.proto.People> peoples_ =
      java.util.Collections.emptyList();
    private void ensurePeoplesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        peoples_ = new java.util.ArrayList<com.test.netty.proto.People>(peoples_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.netty.proto.People, com.test.netty.proto.People.Builder, com.test.netty.proto.PeopleOrBuilder> peoplesBuilder_;

    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public java.util.List<com.test.netty.proto.People> getPeoplesList() {
      if (peoplesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peoples_);
      } else {
        return peoplesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public int getPeoplesCount() {
      if (peoplesBuilder_ == null) {
        return peoples_.size();
      } else {
        return peoplesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public com.test.netty.proto.People getPeoples(int index) {
      if (peoplesBuilder_ == null) {
        return peoples_.get(index);
      } else {
        return peoplesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder setPeoples(
        int index, com.test.netty.proto.People value) {
      if (peoplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeoplesIsMutable();
        peoples_.set(index, value);
        onChanged();
      } else {
        peoplesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder setPeoples(
        int index, com.test.netty.proto.People.Builder builderForValue) {
      if (peoplesBuilder_ == null) {
        ensurePeoplesIsMutable();
        peoples_.set(index, builderForValue.build());
        onChanged();
      } else {
        peoplesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder addPeoples(com.test.netty.proto.People value) {
      if (peoplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeoplesIsMutable();
        peoples_.add(value);
        onChanged();
      } else {
        peoplesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder addPeoples(
        int index, com.test.netty.proto.People value) {
      if (peoplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeoplesIsMutable();
        peoples_.add(index, value);
        onChanged();
      } else {
        peoplesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder addPeoples(
        com.test.netty.proto.People.Builder builderForValue) {
      if (peoplesBuilder_ == null) {
        ensurePeoplesIsMutable();
        peoples_.add(builderForValue.build());
        onChanged();
      } else {
        peoplesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder addPeoples(
        int index, com.test.netty.proto.People.Builder builderForValue) {
      if (peoplesBuilder_ == null) {
        ensurePeoplesIsMutable();
        peoples_.add(index, builderForValue.build());
        onChanged();
      } else {
        peoplesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder addAllPeoples(
        java.lang.Iterable<? extends com.test.netty.proto.People> values) {
      if (peoplesBuilder_ == null) {
        ensurePeoplesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peoples_);
        onChanged();
      } else {
        peoplesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder clearPeoples() {
      if (peoplesBuilder_ == null) {
        peoples_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        peoplesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public Builder removePeoples(int index) {
      if (peoplesBuilder_ == null) {
        ensurePeoplesIsMutable();
        peoples_.remove(index);
        onChanged();
      } else {
        peoplesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public com.test.netty.proto.People.Builder getPeoplesBuilder(
        int index) {
      return getPeoplesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public com.test.netty.proto.PeopleOrBuilder getPeoplesOrBuilder(
        int index) {
      if (peoplesBuilder_ == null) {
        return peoples_.get(index);  } else {
        return peoplesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public java.util.List<? extends com.test.netty.proto.PeopleOrBuilder> 
         getPeoplesOrBuilderList() {
      if (peoplesBuilder_ != null) {
        return peoplesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peoples_);
      }
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public com.test.netty.proto.People.Builder addPeoplesBuilder() {
      return getPeoplesFieldBuilder().addBuilder(
          com.test.netty.proto.People.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public com.test.netty.proto.People.Builder addPeoplesBuilder(
        int index) {
      return getPeoplesFieldBuilder().addBuilder(
          index, com.test.netty.proto.People.getDefaultInstance());
    }
    /**
     * <code>repeated .com.test.netty.proto.People peoples = 1;</code>
     */
    public java.util.List<com.test.netty.proto.People.Builder> 
         getPeoplesBuilderList() {
      return getPeoplesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.netty.proto.People, com.test.netty.proto.People.Builder, com.test.netty.proto.PeopleOrBuilder> 
        getPeoplesFieldBuilder() {
      if (peoplesBuilder_ == null) {
        peoplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.netty.proto.People, com.test.netty.proto.People.Builder, com.test.netty.proto.PeopleOrBuilder>(
                peoples_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        peoples_ = null;
      }
      return peoplesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.test.netty.proto.PeopleList)
  }

  // @@protoc_insertion_point(class_scope:com.test.netty.proto.PeopleList)
  private static final com.test.netty.proto.PeopleList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.netty.proto.PeopleList();
  }

  public static com.test.netty.proto.PeopleList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeopleList>
      PARSER = new com.google.protobuf.AbstractParser<PeopleList>() {
    @java.lang.Override
    public PeopleList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PeopleList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PeopleList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeopleList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.test.netty.proto.PeopleList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

