// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_demo.proto

package com.test.netty.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.test.netty.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>map&lt;string, string&gt; infos = 1;</code>
   */
  boolean containsInfos(
      java.lang.String key);
  /**
   * Use {@link #getInfosMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getInfos();
  /**
   * <code>map&lt;string, string&gt; infos = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getInfosMap();
  /**
   * <code>map&lt;string, string&gt; infos = 1;</code>
   */

  java.lang.String getInfosOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; infos = 1;</code>
   */

  java.lang.String getInfosOrThrow(
      java.lang.String key);
}
